### ISSUE TITLE
sassc produces invalid css selectors

### ISSUE THREAD

**Issue by dreyks** [sass/sassc#180]
given an scss snippet

```scss
 .base-class {
   color: #FFF;
 }

 .parent-class {
   .child-class {
     @extend .base-class;
     border: '1px';
   }
 }

 *:not(.base-class) {
   display: none;
 }
```

sassc produces the following css

```css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class):not(.parent-class .child-class) {
  display: none; }
```

the last selector is invalid. Ruby sass implementation recognizes the impossibility to negate the compund class and gives up altogether, producing valid css
```css
.base-class, .parent-class .child-class {
  color: #FFF; }

.parent-class .child-class {
  border: '1px'; }

*:not(.base-class) {
  display: none; }
```

System info
```console
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ sassc -v
sassc: 3.3.6-10-g2075
libsass: 3.3.6-81-g6610
sass2scss: 1.0.6
sass: 3.4
