### ISSUE TITLE
Segfault 11 on scss file

### ISSUE THREAD

**Issue by niveuseverto** [sass/sassc#2]
test.scss:

``` css
$blue: #3bbfce;
$margin: 16px;

.content-navigation {
  border-color: $blue;
  color: darken($blue, 9%);
  .test {
    background: url('image.png');
  }
}

.border {
  padding: $margin / 2;
  margin: $margin / 2;
  border-color: $blue;
}
```

Output: $ bin/sassc test.scss 
Segmentation fault: 11
