### ISSUE TITLE
sourcemap is not generated

### ISSUE THREAD

**Issue by faebser** [sass/sassc#207]
# Issue

Running sassc on arch linux with either of the ```-m``` or ```--sourcemap``` switches does not generate a sourcemap file.

`sassc --sourcemap fonts.scss fonts.css` only generates a fonts.css file and while `sass --sourcemap=file fonts.scss fonts.css` generates a fonts.css and a  fonts.css.map file.

# Version

output of ```sassc --version```:
```
sassc: na
libsass: na
sass2scss: 1.1.0
sass: 3.4
```

pacman output:
`community/sassc 3.3.6-1 [installed]`

# Testcase

```css
@font-face {
    font-family: 'noto_sansbold';
    src: url('fonts/notosans-bold-webfont.woff2') format('woff2'),
         url('fonts/notosans-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'noto_sansregular';
    src: url('fonts/notosans-regular-webfont.woff2') format('woff2'),
         url('fonts/notosans-regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'noto_serifbold';
    src: url('fonts/notoserif-bold-webfont.woff2') format('woff2'),
         url('fonts/notoserif-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'noto_serifregular';
    src: url('fonts/notoserif-regular-webfont.woff2') format('woff2'),
         url('fonts/notoserif-regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

%serif-bold {
    font-family: 'noto_serifbold', serif;
}

%serif-regular {
    font-family: 'noto_serifregular', serif;
}

%sans-bold {
    font-family: 'noto_sansbold', sans-serif;
}

%sans-regular {
    font-family: 'noto_sansregular', sans-serif;
}

%size-m {
    font-size: 1rem;
    line-height: 1.2;
}

%size-l {
    font-size: 1.857142857rem;
    line-height: 1.2;
}

%size-xl {
    font-size: 2.642857143rem;
    line-height: 1.2;
}

%size-xxl {
    font-size: 4.285714286rem;
    line-height: 1;
}
```
