### ISSUE TITLE
Building jekyll site fails

### ISSUE THREAD

**Issue by L1Cafe** [sass/sassc#258]
Not entirely sure how to debug this, but I'll try my best.

This is a strange situation because it seems to work perfectly on my macOS machine (with the same command), whereas it fails on GitLab CI (Docker with the `jekyll/builder:latest image` )

These are the contents of the `.gitlab-ci.yml` file (although I removed some lines for privacy reasons, as they don't get executed anyway):

```
image: jekyll/builder:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build --future -d test
  artifacts:
    paths:
      - test
  except:
    - master

build:
  stage: deploy
  script:
    - bundle exec jekyll build --future -d public
  artifacts:
    paths:
      - public
  only:
    - master

```

And this is the stdout as presented by the GitLab web console:

```
bundle exec jekyll build --future -d test
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
LoadError: Could not open library '/usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/libsass.so': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/libsass.so)
  /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:145:in `block in ffi_lib'
  /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `map'
  /usr/local/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `ffi_lib'
  /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/native.rb:10:in `<module:Native>'
  /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/native.rb:6:in `<module:SassC>'
  /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc/native.rb:5:in `<top (required)>'
  /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc.rb:31:in `require_relative'
  /usr/local/bundle/gems/sassc-2.1.0-x86_64-linux/lib/sassc.rb:31:in `<top (required)>'
  /usr/local/bundle/gems/jekyll-sass-converter-2.0.0/lib/jekyll/converters/scss.rb:3:in `require'
  /usr/local/bundle/gems/jekyll-sass-converter-2.0.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /usr/local/bundle/gems/jekyll-sass-converter-2.0.0/lib/jekyll-sass-converter.rb:4:in `require'
  /usr/local/bundle/gems/jekyll-sass-converter-2.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `require'
  /usr/local/bundle/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
  /usr/local/bundle/gems/jekyll-4.0.0/exe/jekyll:8:in `require'
  /usr/local/bundle/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
  /usr/local/bundle/bin/jekyll:29:in `load'
  /usr/local/bundle/bin/jekyll:29:in `<top (required)>'
```

I am not certain if it's a sassc issue, or an issue with the Docker image I'm using.

If you need further logs, please let me know what you need exactly and how to find it, I will do my best.
