### ISSUE TITLE
Don’t output properties when the value is `null`

### ISSUE THREAD

**Issue by davidaurelio** [sass/sassc#58]
The ruby implementation omits properties when their value is `null`. This behavior can lead to less cluttered code e.g. in mixins.
## Example:

``` scss
@mixin border($top: null, $right: null, $bottom: null, $left: null) {
  border-top: $top;
  border-right: $right;
  border-bottom: $bottom;
  border-left: $left;
}

.box {
  @include border($left: 1px solid);
}
```
### Expected Output

``` css
.box {
  border-left: 1px solid; }
```
### sassc output:

``` css
.box {
  border-top: null;
  border-right: null;
  border-bottom: null;
  border-left: 1px solid; }
```
